# Generated by Django 3.2.16 on 2023-05-08 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('clicksButtons1', models.PositiveIntegerField(default=0)),
                ('clicksButtons2', models.PositiveIntegerField(default=0)),
                ('screenTime', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserRegular',
                'verbose_name_plural': 'UsersRegular',
            },
        ),
    ]
