# Generated by Django 3.2.16 on 2023-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregular',
            options={},
        ),
        migrations.RemoveField(
            model_name='userregular',
            name='user',
        ),
    ]
