# Generated by Django 3.2.16 on 2023-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
