# Generated by Django 3.2.16 on 2023-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='logo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
